### ISSUE TITLE
请问怎样获取或导入cookies？

### ISSUE THREAD

**Issue by ktownag** [elecV2/elecV2P-dei#1]
运行task脚本时没有cookie；
不需要cookie的脚本（比如天气脚本）则提示：The "url" argument must be of type string. Received undefined

**Comment by elecV2** [comment]
cookie 导入和surge/quanx 等软件差不多，设置 rewrite/mitm ，然后通过代理软件把对应域名流量代理到服务器 8001 端口。

出现错误的天气脚本是哪一个？我看一下

**Comment by elecV2** [comment]
> 运行task脚本时没有cookie；
> 不需要cookie的脚本（比如天气脚本）则提示：The "url" argument must be of type string. Received undefined

cookie 导入和surge/quanx 等软件差不多，设置 rewrite/mitm ，然后通过代理软件把对应域名流量代理到服务器 8001 端口。

出现错误的天气脚本是哪一个？我看一下

**Comment by ktownag** [comment]
感谢回复。天气脚本 https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/minute_forecast.js

**Comment by elecV2** [comment]
> 感谢回复。天气脚本 https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/minute_forecast.js

更新一下 runjs/context.js 文件。不过这个脚本好像还是用不了，回头再好好研究一下
