### ISSUE TITLE
TGbotonCFworker2.0 按照教程配置后 机器人报错

### ISSUE THREAD

**Issue by KodoShinichi** [elecV2/elecV2P-dei#10]
大佬可以请教下我配置好CF了 
![746AB4DE-3C7A-490E-A051-1C663B3FE6B8](https://user-images.githubusercontent.com/26167263/109464239-5176de00-7aa1-11eb-86fa-97b6678a52ab.png)

 给 tg bot 添加 webhook也返回了
![80D7F967-1C08-48E9-A622-A341532843BA](https://user-images.githubusercontent.com/26167263/109464177-35733c80-7aa1-11eb-9f5c-cf6f2ae0ee9f.png)
但是机器人还是报错了
![177A9373-C175-41B2-8324-0BD6C2D67E83](https://user-images.githubusercontent.com/26167263/109464220-49b73980-7aa1-11eb-990d-61a44929f040.png)
报错代码：error code: 1003

**Comment by elecV2** [comment]
这应该是你 cfworker 上的返回数据有问题，先用一些简单的数据直接返回测试一下吧。

> 大佬可以请教下我配置好CF了
> 
> 
> 给 tg bot 添加 webhook也返回了
> 
> 但是机器人还是报错了
> 
> 报错代码：error code: 1003
