### ISSUE TITLE
大佬关于github可以执行jdsharedresourcescdn.azureedge.net不能执行的问题

### ISSUE THREAD

**Issue by jiangzuohaoo** [elecV2/elecV2P-dei#11]
大佬你好，我安装好后，为啥github可以执行jdsharedresourcescdn.azureedge.net不能执行？远程下载也下不了，查了日志显示403，ssh后台进去v2p容器后，jdsharedresourcescdn.azureedge.net      ping得通 wget 时又显示403.   本地浏览器是可以访问的。浏览器设置了全局代理也不行。望指教

**Comment by elecV2** [comment]
在 webUI->SETTING 网络相关设置给 elecV2P 添加代理
