### ISSUE TITLE
建议：tgbot的task和cookie的优化

### ISSUE THREAD

**Issue by LevineWoo** [elecV2/elecV2P-dei#16]
首先作者对功能的开发一直在更新，我们也一直在体验着新功能。非常感谢。

然后是建议：
一是task能够以序号而不是tid来输入会比较方便，同时增加删除任何和立即执行任务
二是cookie建议能够以清单查询形式（序号）或模糊查找会比较方便。目前的操作需要完全一致（包括大小写）

**Comment by elecV2** [comment]
序号这个可以考虑一下

删除是 /taskdel taskid

立即执行完全没必要吧？直接用 /runjs 和 /shell 命令就好了。

Cookie 操作特别注重安全性，模糊查询不会有，其他的之后看情况再添加吧

**Comment by LevineWoo** [comment]
> 序号这个可以考虑一下 删除是 /taskdel taskid 立即执行完全没必要吧？直接用 /runjs 和 /shell 命令就好了。 Cookie 操作特别注重安全性，模糊查询不会有，其他的之后看情况再添加吧

明白了，是我没有仔细阅读。谢谢。

另外看了文档，通知中匹配的方法是找到了，但是匹配后不通知是该怎么写？
比如：start scheduletask xxxx 
 stopped xxxx
这些通知是否能关闭？

**Comment by elecV2** [comment]
通知的写法参考说明文档 04-js 和 07-notify。

（之后的版本会添加默认通知的开关选项

**Comment by LevineWoo** [comment]
> 通知的写法参考说明文档 04-js 和 07-notify。 （之后的版本会添加默认通知的开关选项
感谢，但在文档中还是没有找到不通知这个该怎么写。

**Comment by sngxpro** [comment]
@LevineWoo 臣附议👍
