### ISSUE TITLE
建议：TGbot log指令问题及V2P时间问题

### ISSUE THREAD

**Issue by ghost** [elecV2/elecV2P-dei#18]
1. TGbot log指令：可能因为我的log数量有将近100个，会返回Unexpected token e in JSON at position 0；而log数量很少的时候就可以列出列表。请问有没有什么解决方案呢，比如分开？
2. V2P时间：跑那种对时间要求高的脚本，对照日志发现总是有延迟，如果有校正的方法，自己就能依据时间差来修改脚本具体的秒数了。感觉是有些苛刻，但有没有实现方法呢？

感谢作者的辛勤劳动！V2PBot真的好用！！！

**Comment by elecV2** [comment]
log 这个之后会优化一下。

至于延迟，不可能会达到秒数级（这个可以自己在脚本开头加一行 console.log(1) 进行判断）。
如果和现实时间有误差，应该校准一下服务器的时间。
如果是因为脚本自身获取基础信息（比如账号/昵称等）导致的延迟，只能自己修改脚本去避免（比如直接去掉这些步骤，或者提前运行等
