### ISSUE TITLE
TGbot能否添加任务

### ISSUE THREAD

**Issue by ghost** [elecV2/elecV2P-dei#19]
体验了好几周了，也同步更新了。最新有很多新脚本要上传，能不能按照名称+cron+运行JS+链接这种添加方式让bot来添加，就无需打开UI页面了。
谢谢作者！

**Comment by ghost** [comment]
还有如果任务能够自定义排序就好了（不用打开list文件的前提下

**Comment by elecV2** [comment]
BOT 添加任务这个容易出错，可以尝试写个捷径配合webhook 去实现。

排序比较复杂，可能今年年内是不会有的。之后再看情况吧（应该是会添加的

**Comment by ghost** [comment]
感谢作者！今天的更新非常棒，之前几个issue都解决了！

**Comment by CenBoMin** [comment]
> 感谢作者！今天的更新非常棒，之前几个issue都解决了！

https://www.icloud.com/shortcuts/44b0af65a7ac4229a79f044b45c1ab41

之前做的快捷指令，里面要填你的主页地址和webhook token，复制脚本里面下的task local，就可以上传v2p了

10 9 * * * https://raw.githubusercontent.com/age174/-/main/dwyjy.js tag=动物研究院

这个格式和顺序，抓这三个上传
