### ISSUE TITLE
安装后启动错误

### ISSUE THREAD

**Issue by yishuihanbuhan** [elecV2/elecV2P-dei#22]
root@debian10:/elecv2p# docker-compose pull elecv2p && docker-compose up -d
Pulling elecv2p ... done
Removing elecv2p
Recreating 123f9ed9edff_sngxpro ... error

ERROR: for 123f9ed9edff_sngxpro  Cannot start service elecv2p: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: permission denied: unknown

ERROR: for elecv2p  Cannot start service elecv2p: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: permission denied: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by elecV2** [comment]
重装吧。可能是选错镜像了。
https://github.com/elecV2/elecV2P-dei/tree/master/docs/02-Docker.md
