### ISSUE TITLE
有时只有一个task，却会出现任务执行两次的情况

### ISSUE THREAD

**Issue by Sinclair-Liu** [elecV2/elecV2P-dei#26]
如图所示，出现了2次运行（注：只有一个定时为0 1 0 * * *的task）
![image](https://user-images.githubusercontent.com/26570936/133470354-c639b1cb-2a2d-4f86-9901-2b4b81c35f36.png)
昨日也遇到此情况，是另一个定时为0 */10 1-12 * * *的任务，暂停并重新运行，可以恢复正常（因为日志已清，用通知的图展示）。
![image](https://user-images.githubusercontent.com/26570936/133471057-76ad79d0-26b7-46ee-876c-997b7982f5eb.png)

但对于本次每日只运行一次，单次耗时7小时左右的脚本，只能重启解决。

此前未遇到此问题，不确定此bug是否是最近一次软更新后出现。

**Comment by Sinclair-Liu** [comment]
当前版本：VERSION: 3.4.6

**Comment by elecV2** [comment]
自己仔细捋一下任务执行的时间逻辑吧，通常这种情况是上一个任务还没结束，然后又开始了一个新的任务。
