### ISSUE TITLE
8102抓包页面提示error happened when setup websocket

### ISSUE THREAD

**Issue by umbrellax** [elecV2/elecV2P-dei#28]
自己是通过蜂窝网络开启http代理自己公网ip+8101后抓的包  头几天都正常 就前天开始抓不了包了  尝试重启v2p 卸载重装  换wifi开启手动代理  都不行 不知道什么原因
![Screenshot_20211021_125115](https://user-images.githubusercontent.com/3609430/138480001-e6a7106a-f0de-4fbb-adcd-5bbcd37fdd9e.jpg)

**Comment by umbrellax** [comment]
![Screenshot_20211023_114614](https://user-images.githubusercontent.com/3609430/138541341-ec79ff2c-945f-4365-b929-8e01e3a75c62.jpg)
![Screenshot_20211023_101913](https://user-images.githubusercontent.com/3609430/138541342-837cf77e-55fc-4c74-ae1c-a93d5c6d05cb.jpg)
![Screenshot_20211023_114645](https://user-images.githubusercontent.com/3609430/138541345-220a1820-e661-4230-ac04-fd0f9a0283dc.jpg)

**Comment by elecV2** [comment]
根据你提供的信息无法判断出是什么问题。

8102 界面的错误提示可能是你8102对应接口的 websocket 设置有误，无法连接。
具体得打开后台，看后台运行日志才清楚。

**Comment by umbrellax** [comment]
![Screenshot_20211023_154822](https://user-images.githubusercontent.com/3609430/138548146-54f0be91-0f10-4520-9a2e-b8c76b9cdfd3.jpg)
![Screenshot_20211023_153742](https://user-images.githubusercontent.com/3609430/138548150-ce153910-7a6e-44e7-a2bf-f667b76683d6.jpg)
![Screenshot_20211023_153639](https://user-images.githubusercontent.com/3609430/138548153-30dc1743-b633-4519-8b10-c798b715e9d7.jpg)
![Screenshot_20211023_155913](https://user-images.githubusercontent.com/3609430/138548139-0bdaf1b2-ad80-43f9-aef3-d57fd54ba09d.jpg)
你好 这个情况像是mitm没开一样 解析不了https 但是mitm里面域名已经开启 就是之前就是好好的 就一下子突然不能用了 不能自动抓取相关内容了  ，另外还需要提供什么吗

**Comment by elecV2** [comment]
“之前好好的，突然不能用了”这种问题，基本上没办法解答，我不知道你操作什么，只能你自己去排查问题。

看后台日志的意思是：使用 docker logs elecv2p 等类似命令看后台运行日志。
或者进容器内使用 pm2 logs 0
(具体怎么操作，或使用命令自行搜索

**Comment by umbrellax** [comment]
我在“初始化相关设置里重启了v2p，然后在docker日志里导出了相关日志， 具体操作如下：重启完，开启anyproxy端口，然后开启http代理链接公网ip，并打开8102抓包后台，然后打开相应软件开始抓包，然后就出错。日志截取的也是从重启v2p之后的日志。麻烦大佬了！解决了给大佬捐杯奶茶💰表达心意！日志穿不了，现在上传个直链html一步查看！[v2p.html](http://nobb.cc/v2p.html)

**Comment by umbrellax** [comment]
作者大大还在嘛

**Comment by umbrellax** [comment]
就是https解析不了  mitm无问题  证书也安装了 就是提示error happened when setup websocket
