### ISSUE TITLE
怎么获取某个执行js的命令

### ISSUE THREAD

**Issue by tcmws** [elecV2/elecV2P-dei#29]
您好，我想把九章看书的软件自己拉出来用命令行跑，因为这个不能多个账户，所以想知道，怎么在命令行输入命令执行task里面的指定脚本，谢谢

**Comment by elecV2** [comment]
哪一个命令行？服务器？elecV2P docker/webUI?
如果是普通的 JS 脚本，可使用 node xxx.js。
如果是 elecV2P 专用脚本，暂时没有通过命令行执行的方式。
