### ISSUE TITLE
关于cookie导入远程js及能不能增加钉钉通知

### ISSUE THREAD

**Issue by SuMaiKaDe** [elecV2/elecV2P-dei#3]
使用定时任务，如果是远程js文件，怎么样能把本地保存的cookie信息插入到js里啊？
还有个请求，能不能增加钉钉通知啊

**Comment by elecV2** [comment]
正常情况下 js 会自动读取，如果有的话。webUI->JSMANAGE store/cookie 管理部分存放了所有本地保存的 cookie 信息。（此类基础性问题今后不在回复。）

不会增加钉钉通知。

> 使用定时任务，如果是远程js文件，怎么样能把本地保存的cookie信息插入到js里啊？
> 还有个请求，能不能增加钉钉通知啊

**Comment by SuMaiKaDe** [comment]
感谢大佬解答，刚接触，不太懂。
我是想定时运行远程js，然后他可以自动获取我保存在jsmanage里的cookie信息吗？需要做其他的处理吗？
