### ISSUE TITLE
最近的boxjs版本都不兼容elecv2p了

### ISSUE THREAD

**Issue by jinshuqishi2019** [elecV2/elecV2P-dei#33]
使用最新的版本boxjs都打开网页显示超时了，使用[老版本](https://github.com/chavyleung/scripts/raw/9008c53a491f711823d708fd5203e556556bbf0b/box/chavy.boxjs.js)可以打开，大佬可以考虑适配的问题吗？毕竟脚本更新改动也蛮多了。

**Comment by elecV2** [comment]
暂时直接用 旧版本最后的 ENV 函数替换新版本中的 ENV ，就是最后一行，function Env 那一部分。 （目前不知道什么问题导致的
