### ISSUE TITLE
搞个交流群呢 

### ISSUE THREAD

**Issue by zhanghaifei1997** [elecV2/elecV2P-dei#5]
搞个交流群呢

**Comment by elecV2** [comment]
目前用户应该还不是很多，没必要。而且个人不大喜欢 QQ群/微信群这些，如果有必要可以上 TG。

> 搞个交流群呢

**Comment by zhanghaifei1997** [comment]
可以啊，tg群链接有吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elecV2/elecV2P-dei"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 上午9:12
收件人:&nbsp;"elecV2/elecV2P-dei"<elecV2P-dei@noreply.github.com&gt;;
抄送:&nbsp;"亚特兰蒂斯之夜"<2428669833@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [elecV2/elecV2P-dei] 搞个交流群呢  (#5)





 
 目前用户应该还不是很多，没必要。而且个人不大喜欢 QQ群/微信群这些，如果有必要可以上 TG。 
 
 &gt; 搞个交流群呢

**Comment by elecV2** [comment]
新开的 TG 交流群：https://t.me/elecV2G (主要为方便群友使用交流，群主24小时不在线，也不负责解答任何问题。)

如果遇到问题还是建议开一个 issue，并注明使用平台，版本，以及附上相关的错误日志。

> 可以啊，tg群链接有吗
