### ISSUE TITLE
增加后台登录密码

### ISSUE THREAD

**Issue by Oscar1011** [elecV2/elecV2P-dei#6]
能否增加个。 不然开了远程访问感觉不太安全。。

**Comment by elecV2** [comment]
不会添加这个。

有需要可以在 设置 (setting) 界面记下 webhook token ，然后限制所有 IP 访问（黑名单填写 * )。然后自己通过 http://你的域名/?token=webhook token 访问

> 能否增加个。 不然开了远程访问感觉不太安全。。
