### ISSUE TITLE
请教下，有现成的js脚本和抓取的cookie，运行js脚本时，怎样把cookie导入到运行的脚本文件中？

### ISSUE THREAD

**Issue by licky009** [elecV2/elecV2P-dei#7]
请教下，有现成的js脚本和抓取的cookie，运行js脚本时，怎样把cookie导入到运行的脚本文件中？

**Comment by elecV2** [comment]
这类基础使用问题，看一下教程吧。

https://github.com/elecV2/elecV2P-dei/tree/master/docs/04-JS.md
