### ISSUE TITLE
能否支持添加解析域名级的白名单

### ISSUE THREAD

**Issue by shishixiu** [elecV2/elecV2P-dei#8]
大佬你好，因为是家庭网络，ip是动态的，我设置了解析域名，可以让白名单支持我设置的域名下绑定的ip吗？

**Comment by elecV2** [comment]
看不懂你的这个需求。

意思是想要只能通过这个域名吗？不知道这个域名的就不让访问？

别人都不知道域名，怎么访问呢？动态IP更加不可能知道。如果知道域名，你这个白名单的意义在哪里？

> 大佬你好，因为是家庭网络，ip是动态的，我设置了解析域名，可以让白名单支持我设置的域名下绑定的ip吗？

**Comment by shishixiu** [comment]
就是这个域名的ip是我路由器拨号的ip，我在这个wifi下也是属于这个ip的

**Comment by elecV2** [comment]
> 就是这个域名的ip是我路由器拨号的ip，我在这个wifi下也是属于这个ip的

应该不会支持这个。如果不确定 IP 的话，建议直接屏蔽所有 IP ，然后通过 token 访问  xxx.com/?token=webhook token
