### ISSUE TITLE
脚本启动过程有俩error

### ISSUE THREAD

**Issue by skybbk1001** [elecV2/elecV2P-dei#9]
![Screenshot_2021-03-01-01-02-41-896_com termux](https://user-images.githubusercontent.com/70464410/109426720-07064a80-7a2a-11eb-9fd4-e58d0ef9d50f.jpg)
elecv2p可以正常启动，这两个error如何处理

**Comment by elecV2** [comment]
谷歌
（这不是elecV2P 导致的问题，如果不影响使用就忽略。）

> 
> elecv2p可以正常启动，这两个error如何处理
